name: Deploy AWS Services

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-lambda:
    name: Deploy Scraper to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if needed

      - name: Zip and Deploy AWS Lambda
        run: |
          cd lambda_scraper
          zip -r function.zip .
          aws lambda update-function-code --function-name air-monitoring-scraper --zip-file fileb://function.zip

  deploy-dash:
    name: Deploy Dash App to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: deploy-lambda  # Runs only after Lambda is deployed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if needed

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          cd dash_app
          zip -r deploy.zip .
          aws elasticbeanstalk create-application-version --application-name AirMonitoringDash --version-label latest --source-bundle S3Bucket="my-app-bucket",S3Key="deploy.zip"
          aws elasticbeanstalk update-environment --application-name AirMonitoringDash --environment-name AirMonitoringEnv --version-label latest
